services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: refrncp_app
        restart: unless-stopped
        env_file:
            - .env.docker.prod
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./data:/app/data
            - ./certs:/certs:ro
