<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260415134833 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, position INT NOT NULL, framework_id INT NOT NULL, block_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E3DE47737AECF72 ON skill (framework_id)');
        $this->addSql('CREATE INDEX IDX_5E3DE477E9ED820C ON skill (block_id)');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE47737AECF72 FOREIGN KEY (framework_id) REFERENCES framework (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE477E9ED820C FOREIGN KEY (block_id) REFERENCES block (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE skill DROP CONSTRAINT FK_5E3DE47737AECF72');
        $this->addSql('ALTER TABLE skill DROP CONSTRAINT FK_5E3DE477E9ED820C');
        $this->addSql('DROP TABLE skill');
    }
}
