<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260415134514 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, duration_days INT DEFAULT NULL, duration_hours INT DEFAULT NULL, objectives TEXT DEFAULT NULL, prerequisites TEXT DEFAULT NULL, position INT NOT NULL, promotion_id INT NOT NULL, block_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE139DF194 ON project (promotion_id)');
        $this->addSql('CREATE INDEX IDX_2FB3D0EEE9ED820C ON project (block_id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE139DF194 FOREIGN KEY (promotion_id) REFERENCES promotion (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEE9ED820C FOREIGN KEY (block_id) REFERENCES block (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EE139DF194');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EEE9ED820C');
        $this->addSql('DROP TABLE project');
    }
}
