<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260415135149 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE evaluation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, modalities JSON DEFAULT NULL, validation_rules JSON DEFAULT NULL, position INT NOT NULL, framework_id INT NOT NULL, block_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1323A57537AECF72 ON evaluation (framework_id)');
        $this->addSql('CREATE INDEX IDX_1323A575E9ED820C ON evaluation (block_id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A57537AECF72 FOREIGN KEY (framework_id) REFERENCES framework (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575E9ED820C FOREIGN KEY (block_id) REFERENCES block (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A57537AECF72');
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A575E9ED820C');
        $this->addSql('DROP TABLE evaluation');
    }
}
